### ISSUE TITLE
Another error in redmine 2.6

### ISSUE THREAD

**Issue by dominch** [jrupesh/redmine_query_share#3]
When trying to share saved query I got: 

```
NoMethodError in QueriesController#update
undefined method `association_class' for nil:NilClass
```

Full stack trace: 

```
activerecord (3.2.22) lib/active_record/associations.rb:160:in `association'
activerecord (3.2.22) lib/active_record/associations/builder/association.rb:44:in `block in define_readers'
plugins/redmine_query_share/lib/query_share/patches/query_patch.rb:31:in `block (2 levels) in included'
activesupport (3.2.22) lib/active_support/callbacks.rb:464:in `_run__1775213225943011472__save__3805818121486462485__callbacks'
activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.22) lib/active_support/callbacks.rb:385:in `_run_save_callbacks'
activesupport (3.2.22) lib/active_support/callbacks.rb:81:in `run_callbacks'
activerecord (3.2.22) lib/active_record/callbacks.rb:264:in `create_or_update'
activerecord (3.2.22) lib/active_record/persistence.rb:84:in `save'
activerecord (3.2.22) lib/active_record/validations.rb:50:in `save'
activerecord (3.2.22) lib/active_record/attribute_methods/dirty.rb:22:in `save'
activerecord (3.2.22) lib/active_record/transactions.rb:259:in `block (2 levels) in save'
activerecord (3.2.22) lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
activerecord (3.2.22) lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
activerecord (3.2.22) lib/active_record/transactions.rb:208:in `transaction'
activerecord (3.2.22) lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
activerecord (3.2.22) lib/active_record/transactions.rb:259:in `block in save'
activerecord (3.2.22) lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
activerecord (3.2.22) lib/active_record/transactions.rb:258:in `save'
app/controllers/queries_controller.rb:80:in `update'
plugins/extra_queries/lib/extra_queries/queries_controller_patch.rb:33:in `update_with_eq'
actionpack (3.2.22) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.22) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.22) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.22) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.22) lib/active_support/callbacks.rb:524:in `_run__2809639504148318299__process_action__2370013523853049462__callbacks'
activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.22) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.22) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.22) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.22) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.22) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.22) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.22) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.22) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.22) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.2.22) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.22) lib/abstract_controller/rendering.rb:45:in `process'
rack-mini-profiler (0.9.7) lib/mini_profiler/profiling_methods.rb:77:in `block in profile_method'
actionpack (3.2.22) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.22) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.22) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:608:in `call'
rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.7) lib/rack/etag.rb:23:in `call'
rack (1.4.7) lib/rack/conditionalget.rb:35:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/cookies.rb:341:in `call'
activerecord (3.2.22) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.2.22) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `_run__2768398243053684469__call__3805818121486462485__callbacks'
activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.22) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.22) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.22) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/reloader.rb:65:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.22) lib/rails/rack/logger.rb:32:in `call_app'
railties (3.2.22) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.22) lib/active_support/tagged_logging.rb:22:in `tagged'
railties (3.2.22) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.7) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.22) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.7) lib/rack/lock.rb:15:in `call'
actionpack (3.2.22) lib/action_dispatch/middleware/static.rb:83:in `call'
rack-mini-profiler (0.9.7) lib/mini_profiler/profiler.rb:170:in `call'
railties (3.2.22) lib/rails/engine.rb:484:in `call'
railties (3.2.22) lib/rails/application.rb:231:in `call'
railties (3.2.22) lib/rails/railtie/configurable.rb:30:in `method_missing'
passenger (5.0.5) lib/phusion_passenger/rack/thread_handler_extension.rb:85:in `process_request'
passenger (5.0.5) lib/phusion_passenger/request_handler/thread_handler.rb:155:in `accept_and_process_next_request'
passenger (5.0.5) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
passenger (5.0.5) lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
passenger (5.0.5) lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
```

This gives error 500 :(

**Comment by jrupesh** [comment]
Hi 
Have you run the migration command?

rake redmine:plugins:migrate NAME=redmine_query_share

Thanks.

**Comment by dominch** [comment]
yes, sure, this task is run often in my migation script 
problem is still present :( I'm using latest 2.x version

**Comment by jrupesh** [comment]
I guess you are using another plugin -> extra_queries
This has broken the current one.

**Comment by dominch** [comment]
@jrupesh hello, thanks for Your help. Indeed I'm using this plugin and so far nobody reported any error with it. I'm guess that they conflicting each other. I'll remove one of them. 
Thanks for Your help!
